<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260128163150 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, description TEXT NOT NULL, hazard_tags JSON NOT NULL, sector_tags JSON NOT NULL, effort VARCHAR(10) NOT NULL, cost VARCHAR(10) NOT NULL, impact VARCHAR(10) NOT NULL, horizon VARCHAR(10) NOT NULL, prerequisites TEXT DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE admin_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hazard_weights_json JSON NOT NULL, thresholds_json JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(255) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, input_activity_type VARCHAR(100) DEFAULT NULL, input_building_type VARCHAR(100) DEFAULT NULL, input_has_basement BOOLEAN NOT NULL, input_criticality VARCHAR(50) DEFAULT NULL, status VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9218FF79A76ED395 ON audit (user_id)');
        $this->addSql('CREATE TABLE audit_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scores_json JSON NOT NULL, levels_json JSON NOT NULL, confidence_score INT NOT NULL, explanations_json JSON NOT NULL, recommendations_json JSON NOT NULL, data_sources_json JSON NOT NULL, computed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, audit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_30B4EDC8BD29F359 ON audit_result (audit_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_session_id VARCHAR(255) NOT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, status VARCHAR(30) NOT NULL, amount INT NOT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, audit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840DBD29F359 ON payment (audit_id)');
        $this->addSql('CREATE TABLE pdf_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, path_or_key VARCHAR(255) DEFAULT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, audit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2B8DB03BD29F359 ON pdf_report (audit_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE audit ADD CONSTRAINT FK_9218FF79A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE audit_result ADD CONSTRAINT FK_30B4EDC8BD29F359 FOREIGN KEY (audit_id) REFERENCES audit (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DBD29F359 FOREIGN KEY (audit_id) REFERENCES audit (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pdf_report ADD CONSTRAINT FK_A2B8DB03BD29F359 FOREIGN KEY (audit_id) REFERENCES audit (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit DROP CONSTRAINT FK_9218FF79A76ED395');
        $this->addSql('ALTER TABLE audit_result DROP CONSTRAINT FK_30B4EDC8BD29F359');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DBD29F359');
        $this->addSql('ALTER TABLE pdf_report DROP CONSTRAINT FK_A2B8DB03BD29F359');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE admin_config');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE audit');
        $this->addSql('DROP TABLE audit_result');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE pdf_report');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
